// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("goauto")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/goautoreceiver"
)

const (
	TracesStability = component.StabilityLevelDevelopment
)
